{% set name = "kubernetes-cloud-provider-kind" %}
{% set version = "0.11.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/kubernetes-sigs/cloud-provider-kind/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 87a8c713be6b0635f7cd32832c40a929afd93ddffc57a03076a7574bd7dfc43c

build:
  number: 0
  skip: true  # [win]
  script:
    - go-licenses save . --save_path library_licenses
    - go build -v -o $PREFIX/bin/cloud-provider-kind

requirements:
  build:
    - {{ compiler('go-nocgo') }}
    - go-licenses

test:
  commands:
    - cloud-provider-kind --help

about:
  home: https://github.com/kubernetes-sigs/cloud-provider-kind
  license: Apache-2.0
  license_file:
    - LICENSE
    - library_licenses/
  summary: Cloud provider for KIND clusters

extra:
  recipe-maintainers:
    - borchero
