{% set name = "kubernetes-cloud-provider-kind" %}
{% set version = "0.5.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/kubernetes-sigs/cloud-provider-kind/archive/refs/tags/v{{ version }}.tar.gz
  sha256: ba3fad794370b1ff14e608edfa5883cb455e1e6e89d6a63187c5f47bf4e23251

build:
  number: 0
  skip: true  # [win]
  script:
    - go-licenses save . --save_path library_licenses
    - go build -v -o $PREFIX/bin/cloud-provider-kind

requirements:
  build:
    - {{ compiler('go-nocgo') }}
    - go-licenses

test:
  commands:
    - cloud-provider-kind --help

about:
  home: https://github.com/kubernetes-sigs/cloud-provider-kind
  license: Apache-2.0
  license_file:
    - LICENSE
    - library_licenses/
  summary: Cloud provider for KIND clusters

extra:
  recipe-maintainers:
    - borchero
