{% set name = "kubernetes-cloud-provider-kind" %}
{% set version = "0.10.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/kubernetes-sigs/cloud-provider-kind/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 447ce982e8103934c92a466438cad961a7ca3f817534c3b53c80b12929679b95

build:
  number: 0
  skip: true  # [win]
  script:
    - go-licenses save . --save_path library_licenses
    - go build -v -o $PREFIX/bin/cloud-provider-kind

requirements:
  build:
    - {{ compiler('go-nocgo') }}
    - go-licenses

test:
  commands:
    - cloud-provider-kind --help

about:
  home: https://github.com/kubernetes-sigs/cloud-provider-kind
  license: Apache-2.0
  license_file:
    - LICENSE
    - library_licenses/
  summary: Cloud provider for KIND clusters

extra:
  recipe-maintainers:
    - borchero
